name: discover_ease
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.0
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.10
  firebase_analytics: ^10.9.0
  permission_handler: ^11.3.1
  get: ^4.6.6
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  latlng: ^2.0.7
  flutterfire_cli: ^1.0.1-dev.0
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  chat_bubbles: ^1.0.0+3
  shared_preferences: ^2.0.13 
  line_icons: ^2.0.3
  google_fonts: ^6.2.1
  curved_labeled_navigation_bar: ^2.0.2
  floating_bottom_bar: ^0.0.3
  introduction_screen: ^3.1.14
  fab_circular_menu: ^1.0.0
  flutter_polyline_points:
  flip_card:
  flutter_rating_stars:
  flutter_riverpod:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/city/
    - assets/logo.png
    - assets/onboarding_1.png
    - assets/onboarding_2.png
    - assets/city/entry_page.png
    - assets/city/profile.png
    - assets/city/city15.jpg
    - assets/profile_images/im1.png  
    - assets/profile_images/im2.png  
    - assets/profile_images/im3.png  
    - assets/profile_images/im4.png  
    - assets/profile_images/im5.png  
    - assets/profile_images/im6.png  
    - assets/profile_images/im7.png  
    - assets/profile_images/im8.png  
    - assets/profile_images/im9.png  
    - assets/profile_images/im10.png  
    - assets/profile_images/im11.png
    - assets/mapicons/
